<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/16 0016
 * Time: 14:13
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class AccessLog extends ActiveRecord
{
    public static function tableName()
    {
        return 'access_log'; // TODO: Change the autogenerated stub
    }
}