<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/01/09 0009
 * Time: 15:44
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Count extends ActiveRecord
{
    public static function tableName()
    {
        return "{{count}}"; // TODO: Change the autogenerated stub
    }
}