<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/01/10 0010
 * Time: 20:16
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Last extends ActiveRecord
{
    public static function tableName()
    {
        return "{{last_month}}"; // TODO: Change the autogenerated stub
    }
}