<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/20 0020
 * Time: 14:38
 */
namespace statistics\models;


use yii\db\ActiveRecord;

class Page extends ActiveRecord
{
    public static function tableName()
    {
        return 'page'; // TODO: Change the autogenerated stub
    }
}