<?php
/**
 * Created by PhpStorm.
 * User: MMCCoder
 * Date: 2016/11/16 0016
 * Time: 上午 10:46
 */
namespace statistics\models;

use yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;

class Scount extends yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'scount'; // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}