<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/01/09 0009
 * Time: 12:05
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Type extends ActiveRecord
{
    public static function tableName()
    {
        return "type"; // TODO: Change the autogenerated stub
    }
}