<?php
/**
 * Created by PhpStorm.
 * User: MMCCoder
 * Date: 2016/11/17 0017
 * Time: 上午 9:42
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Webs extends ActiveRecord
{
    public static function tableName()
    {
        return 'domain'; // TODO: Change the autogenerated stub
    }
}