<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/01/09 0009
 * Time: 10:19
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Week extends ActiveRecord
{
    public static function tableName()
    {
        return "{{week_count}}"; // TODO: Change the autogenerated stub
    }
}