<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/01/09 0009
 * Time: 10:17
 */
namespace statistics\models;

use yii\db\ActiveRecord;

class Yesterday extends ActiveRecord
{
    public static function tableName()
    {
        return "{{yesterday_count}}"; // TODO: Change the autogenerated stub
    }
}